root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/tux_triarch"
entrypoint = ["./tmp/main"]
args_bin = ["serve"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
poll = false
poll_interval = 500                                                # ms
delay = 0                                                          # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500                                                   # nanosecond
rerun = false
rerun_delay = 500

[log]
time = false
main_only = false
silent = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = true
keep_scroll = true

[proxy]
enabled = true
proxy_port = 8079
app_port = 8090
